version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.17.0
  pre_build:
    commands:
      - echo Installing dependencies ...
      - npm ci
  build:
    commands:
      - echo Build Started
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
