version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.17.0
  pre_build:
    commands:
      - echo Installing dependencies ...
      - npm ci
  build:
    commands:
      - echo Build Started
      - npm run build
  post_build:
    commands:
      - echo old version s3 remove
      - aws s3 rm --debug s3://drag-smartfarm-dev-s3 --recursive
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
