version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies ...
      - npm ci
  build:
    commands:
      - echo Build Started
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directry: 'dist'
